auth:
  type: LOGIN_FORM

spring:
  security:
    user:
      name: admin
      password: admin

kafka:
  clusters:
    -
      name: kafka
      bootstrapServers: kafka:29092
      ksqlDbServer: http://ksqldb:8088
      schemaRegistry: http://schema-registry:8081
      kafkaConnect:
        -
         name: connect
         address: http://connect:8083